@echo off
echo =========================================
echo  CDGI Sports - Starting Environment...
echo =========================================
echo Installing dependencies...
call npm install
echo.
echo Launching browser...
start http://localhost:3000
echo.
echo Starting Development Server...
call npm run dev
