/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
      "./pages/**/*.{js,ts,jsx,tsx,mdx}",
      "./components/**/*.{js,ts,jsx,tsx,mdx}",
      "./app/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
            colors: {
                "secondary-fixed-dim": "#37d4ff",
                "outline": "#767577",
                "on-error-container": "#ffd2c8",
                "tertiary-container": "#7000ff",
                "on-primary-fixed": "#314a00",
                "on-surface": "#f9f5f8",
                "on-surface-variant": "#adaaad",
                "surface-bright": "#2c2c2f",
                "secondary-container": "#00677f",
                "tertiary-fixed": "#bda1ff",
                "primary-fixed-dim": "#abee25",
                "primary-fixed": "#b8fd37",
                "on-primary-container": "#314900",
                "secondary": "#00cffc",
                "primary": "#b8fd37",
                "error-dim": "#d53d18",
                "tertiary-dim": "#874cff",
                "on-primary": "#405e00",
                "inverse-primary": "#476900",
                "error": "#ff7351",
                "tertiary": "#ac89ff",
                "surface-dim": "#0e0e10",
                "surface-container-high": "#1f1f22",
                "surface-container-highest": "#262528",
                "surface-container-lowest": "#000000",
                "on-primary-fixed-variant": "#476900",
                "on-tertiary-fixed": "#1f0052",
                "background": "#0e0e10",
                "on-tertiary-fixed-variant": "#4700a7",
                "primary-container": "#9bdd03",
                "outline-variant": "#48474a",
                "inverse-on-surface": "#565457",
                "on-secondary-fixed-variant": "#00586d",
                "primary-dim": "#abee25",
                "surface": "#0e0e10",
                "on-background": "#f9f5f8",
                "surface-variant": "#262528",
                "on-secondary-fixed": "#003a48",
                "inverse-surface": "#fcf8fb",
                "error-container": "#b92902",
                "secondary-fixed": "#80deff",
                "on-tertiary-container": "#f8f1ff",
                "surface-container-low": "#131315",
                "on-error": "#450900",
                "surface-tint": "#b8fd37",
                "secondary-dim": "#00c0ea",
                "surface-container": "#19191c",
                "tertiary-fixed-dim": "#b190ff",
                "on-secondary-container": "#eef9ff",
                "on-tertiary": "#290067",
                "on-secondary": "#004050"
            },
            borderRadius: {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            fontFamily: {
                "headline": ["Space Grotesk", "sans-serif"],
                "body": ["Manrope", "sans-serif"],
                "label": ["Space Grotesk", "sans-serif"]
            }
        },
    },
    plugins: [],
}
